@startuml

class User << entity >> {
    userId: String
    fullName: String
    emailAddress: String
    dateOfBirth: Date
}
class Group << entity >> {
    groupName: String
    description: String
}
class GroupMember << entity >> {
    enabled: boolean
}

GroupMember -right-> Group: group
User <-up- GroupMember: user

@enduml