@startuml

package "AngularJS UI" {
    [NavController] << controller >>
    [NotificationService] << service >>
    [UserController] << controller >>
    [UserService] << service >>
    [UserDialogController] << controller >>
    [UserController] -down-> [UserService]
    [UserController] -down-> [NotificationService]
    [UserDialogController] -down-> [UserService]
    [UserService] -right-> rest : http
    [GroupController] << controller >>
    [GroupService] << service >>
    [GroupDialogController] << controller >>
    [GroupDialogController] -down-> [UserService]
    [GroupController] -down-> [GroupService]
    [GroupController] -down-> [NotificationService]
    [GroupDialogController] -down-> [GroupService]
    [GroupService] -left-> rest : http
    [MemberController] -down-> [MemberService]
    [MemberController] -> [NotificationService]
    [MemberController] -down-> [UserService]
    [MemberService] -> rest : http
}

package "Spring Data Rest Server" {
    [UserInfo] << entity >>
    [GroupInfo] << entity >>
    [GroupMember] << entity >>
    [UserRepository] << repository >>
    [GroupRepository] << repository >>
    [GroupMemberRepository] << repository >>
    [UserRepository] -> [UserInfo]
    [GroupRepository] -> [GroupInfo]
    [GroupMember] -> [GroupMemberRepository]
    rest - [Spring Data Rest]
    [Spring Data Rest] --> [UserRepository]
    [Spring Data Rest] --> [GroupRepository]
    [Spring Data Rest] --> [GroupMemberRepository]
}

@enduml