@startuml

class User << entity >> {
    userId: String
    fullName: String
    dateOfBirth: Date
    emailAddress: String
}
class Group << entity >> {
    groupName: String
    description: String
}
class GroupMember << entity >> {
    enabled: boolean
}

GroupMember -right-> Group: memberOfgroup
GroupMember -up-> User: member

@enduml