= Spring Data Rest Demo API Guide
Corneil du Plessis;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP verbs.

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

RESTful notes tries to adhere as closely as possible to standard HTTP and REST conventions in its
use of HTTP status codes.

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===


[[overview-hypermedia]]
== Hypermedia

RESTful Notes uses hypermedia and resources include links to other resources in their
responses. Responses are in http://stateless.co/hal_specification.html[Hypertext Application
from resource to resource.
Language (HAL)] format. Links can be found beneath the `_links` key. Users of the API should
not create URIs themselves, instead they should use the above-described links to navigate

[[resources]]
= Resources


[[resources-index]]
== Index

The index provides the entry point into the service.


[[resources-index-access]]
=== Accessing the index

A `GET /rest` request is used to access the index

operation::index[snippets='response-fields,curl-request,http-response,links']



[[resources-users]]
== User

The User resources is represents users in the system

[[resources-users-list]]
=== Listing users

A `GET /rest/users` request will list all users.

operation::users-list[snippets='response-fields,curl-request,http-response,links']

[[resources-user-get]]
=== Get a user

A `GET /rest/users/{id}` request will find a specific user

operation::user-get[snippets='path-parameters,response-fields,curl-request,http-response,links']

[[resources-groups]]
== Group

[[resources-groups-list]]
=== List all groups

A `GET /rest/groups` request will list all groups.

operation::groups-list[snippets='response-fields,curl-request,http-response,links']

[[resources-group-get]]
=== Get a group

A `GET /rest/groups/{id}` request will find a specific group

operation::group-get[snippets='path-parameters,response-fields,curl-request,http-response,links']

[[resources-group-search]]
=== Search for group

A `GET /rest/groups/search/findOneByGroupName` request will find users matching a partial name

operation::group-find[snippets='request-parameters,response-fields,curl-request,http-response,links']

[[resources-members]]
== Member

[[resources-member-get]]
=== Get a member

A `GET /rest/members/{id}` request will find a specific group

operation::member-get[snippets='path-parameters,response-fields,curl-request,http-response,links']


[[resources-search]]
== Searches

[[resources-search-user]]
=== Search for users

A `GET /rest/search/users` request will find users matching a partial name

operation::search-users[snippets='request-parameters,response-fields,curl-request,http-response,links']

[[resources-search-members]]
=== Find group members

A `GET /rest/search/members` request will find members of a specified group with enabled indicator

operation::search-members[snippets='request-parameters,response-fields,curl-request,http-response,links']
