#%RAML 1.0
title: Spring Data Rest Demo API
version: v1
protocols: [ HTTP ]
baseUri: http://localhost/api
mediaType: application/json
types:
  User:
    type: object
    properties:
      userId: string
      emailAddress: string
      fullName: string
      dateOfBirth: date-only
      hasImage: boolean
  Group:
    type: object
    properties: # Add groupOwner and members
      description: string
      groupName: string
      groupOwner: User
  GroupMember:
    type: object
    properties: # Add user and group
      enabled: boolean
      group: Group
      user: User
# Note the list of requests is not complete
/users:
  post:
    body:
      type: User
      description: Create a User
    responses:
      200:
        body:
          type: User
/users/{id}:
  get:
    description: Get a User
    responses:
      200:
        body:
          type: User
      404:
        description: User doesn't exist
  put:
    description: Update a User
    body:
      type: User
    responses:
      200:
        body:
          type: User
  delete:
    description: Delete a User
    responses:
        204:
          description: Delete operation completed
        404:
          description: User doesn't exist
/users/search:
  get:
    queryParameters:
      input:
        description: Sub string to match
        type: string
    responses:
      200:
        body:
          type: User[]
/members/search:
  get:
    description: Search for members of specified group
    queryParameters:
      groupName:
        description: Name of Group
        type: string
      enabled?:
        description: If proveded will return members with same state
        type: boolean
    responses:
      200:
        body:
          type: GroupMember[]
